"""Pick, per device, the largest glance date font that fits the WORST-CASE date.

The glance draws the day letter (HebrewGlanceMedium) on the left and the date
(HebrewGlanceSmall) right-aligned; when a date can't fit beside the letter the
view switches to a COMPACT layout (date on the full top line, letter beside the
year). A size fits if, for every worst-case date, one of the two layouts fits. For each product in manifest.xml this
resolves the device's current glance fonts through its monkey.jungle chain,
then finds the largest GlanceSmall size (<= current) for which the longest
day+month string leaves >= PAD px side margins and a >= GAP px gap to the
widest day letter inside the device's glance contentArea width. Devices that
need a smaller size get a glance-only overlay dir resources-gsNN (just
HebrewGlanceSmall at NN px) appended to their resourcePath in monkey.jungle.
Idempotent: re-run after changing buckets/fonts. Verify with
tools/verify/check_glance_fit.py (same numbers) and the sim preview harness.
"""
import json, os, re, sys

sys.path.insert(0, os.path.dirname(__file__))
from PIL import ImageFont
import fontgen

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
DEV = os.path.join(os.environ["APPDATA"], "Garmin", "ConnectIQ", "Devices")
PAD, GAP = 7, 8          # must match HebrewCalendarGlanceView (pad floor 6, -1 rounding)
DATES = ["כ״ט אדר א׳", "כ״ח אדר ב׳", "כ״ט תשרי", "כ״ט כסלו", "כ״ט תמוז"]
LETTERS = "אבגדהוש"
_cache = {}


def adv(size, s):
    """Rendered width: sum of xadvance exactly as fontgen writes them."""
    if size not in _cache:
        f = ImageFont.truetype(fontgen.FONT_PATH, size)
        m = {}
        for ch in fontgen.CHARS:
            b = f.getbbox(ch)
            m[ch] = max(b[2] - b[0] + 2, 2) + 1
        _cache[size] = m
    return sum(_cache[size].get(c, _cache[size][" "]) for c in s)


def chains():
    out = {}
    for line in open(os.path.join(ROOT, "monkey.jungle"), encoding="utf8"):
        m = re.match(r"\s*(\w+)\.resourcePath\s*=\s*\$\(\w+\.resourcePath\);(.*)", line)
        if m:
            out[m.group(1)] = [p.strip() for p in m.group(2).split(";") if p.strip()]
    return out


def size_of(chain, name):
    for d in reversed(["resources"] + chain):
        p = os.path.join(ROOT, d, "fonts", name + ".fnt")
        if os.path.exists(p):
            return int(re.search(r"size=(\d+)", open(p, encoding="utf8").readline()).group(1))
    raise FileNotFoundError(name)


def main():
    devices = re.findall(r'product id="([^"]+)"', open(os.path.join(ROOT, "manifest.xml"), encoding="utf8").read())
    ch = chains()
    need = {}
    for d in devices:
        chain = [p for p in ch.get(d, []) if not re.fullmatch(r"resources-gs\d+", p)]
        w = json.load(open(os.path.join(DEV, d, "simulator.json"), encoding="utf8"))["glance"]["contentArea"]["width"]
        s0 = size_of(chain, "HebrewGlanceSmall")
        m0 = size_of(chain, "HebrewGlanceMedium")
        ltW = max(adv(m0, c) for c in LETTERS)
        def fits(sz):
            for t in DATES:
                dm = adv(sz, t)
                if w - 2 * PAD - ltW - GAP - dm >= 0:
                    continue                      # normal layout
                # compact layout: date on the full top line, letter beside the year
                if dm > w - 2 * 6:
                    return False
                if max(adv(sz, c) for c in LETTERS) + GAP + adv(sz, "תשפ״ח") > w - 2 * 6:
                    return False
            return True
        s = s0
        while s > 10 and not fits(s):
            s -= 1
        need[d] = s if s < s0 else None
        print(f"{d:24s} w={w:3d} glanceSmall {s0} -> {s if s < s0 else '(ok)'}")

    # overlays
    for s in sorted({v for v in need.values() if v}):
        out = os.path.join(ROOT, f"resources-gs{s}", "fonts")
        fontgen.generate_fnt("HebrewGlanceSmall", s, out)
        with open(os.path.join(out, "fonts.xml"), "w", encoding="utf-8") as f:
            f.write('<?xml version="1.0"?>\n<resources>\n'
                    f"    <!-- Glance date font at {s}px so the longest date fits beside the day letter\n"
                    "         (generated by tools/fonts/fit_glance_fonts.py) -->\n"
                    '    <font id="HebrewGlanceSmall" filename="HebrewGlanceSmall.fnt" scope="glance" />\n'
                    "</resources>\n")

    # jungle: strip old resources-gsNN, append the new one where needed
    p = os.path.join(ROOT, "monkey.jungle")
    lines = open(p, encoding="utf8").read().split("\n")
    for i, line in enumerate(lines):
        m = re.match(r"(\s*(\w+)\.resourcePath\s*=\s*.*)$", line)
        if not m or m.group(2) not in need:
            continue
        base = re.sub(r";resources-gs\d+", "", line)
        lines[i] = base + (f";resources-gs{need[m.group(2)]}" if need[m.group(2)] else "")
    open(p, "w", encoding="utf8").write("\n".join(lines))
    print(f"\n{sum(1 for v in need.values() if v)} device(s) got a smaller glance date font")


main()
