"""
Generate Hebrew bitmap fonts for the screen sizes added after v1.6:
  mono166   163-166px MIP semi-octagon (Instinct 2S, Instinct E 40mm)
  mip240    240px MIP round (fenix 6S/7S, MARQ Gen 1, FR945 LTE, Descent Mk2 S)
  mip280    280px MIP round (fenix 6X/7X, Enduro, fenix 8/9 Solar 51mm)
  amoled360 360px AMOLED round (FR265S, Venu 2S) + Venu Sq 2 (320x360)
plus glance-only overlays for glance areas the regular buckets don't fit
(appended after the bucket in monkey.jungle so their glance IDs override):
  glance92     Instinct Crossover AMOLED (340x92 glance)
  glance103    454px devices with a 103px-tall glance (epix Pro 51mm etc.)
  glancexover  Instinct Crossover (hybrid; 110x60 glance)
Glance fit rule (both glance lines use GlanceSmall, centred on cy=h/2):
  LH(GlanceSmall) <= h/2 and (LH(GlanceSmall)+LH(GlanceMedium))/2 <~ h/2 + 8%.
Each bucket also gets a fonts.xml (glance fonts scope="glance").
Uses NotoSansHebrew-Regular from Garmin's own font library.
"""

from PIL import Image, ImageDraw, ImageFont
import os

CHARS = (
    "אבגדהוזחטיכךלמםנןסעפףצץקרשת"
    "׳״־"
    " ():-"
    "0123456789"
)

FONT_PATH = r"C:\Users\yosef\AppData\Roaming\Garmin\ConnectIQ\Fonts\NotoSansHebrew-Regular.ttf"


def generate_fnt(name, size_px, out_dir):
    font = ImageFont.truetype(FONT_PATH, size_px)

    # Real vertical metrics so descenders (e.g. final nun ן) are not clipped.
    ascent, descent = font.getmetrics()
    line_height = ascent + descent

    glyphs = []
    for ch in CHARS:
        bbox = font.getbbox(ch)
        w = max(bbox[2] - bbox[0] + 2, 2)
        h = max(bbox[3] - bbox[1] + 2, 2)
        glyphs.append((ch, w, h, bbox))

    padding = 2
    tex_w = 512
    x, y = padding, padding
    row_h = 0
    positions = []

    for ch, w, h, bbox in glyphs:
        if x + w + padding > tex_w:
            x = padding
            y += row_h + padding
            row_h = 0
        positions.append((ch, x, y, w, h, bbox))
        if h > row_h:
            row_h = h
        x += w + padding

    tex_h = y + row_h + padding
    tex_h_pow2 = 1
    while tex_h_pow2 < tex_h:
        tex_h_pow2 <<= 1

    img = Image.new("RGBA", (tex_w, tex_h_pow2), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)

    fnt_lines = []
    fnt_lines.append(f'info face="{name}" size={size_px} bold=0 italic=0 charset="" unicode=1 stretchH=100 smooth=1 aa=1 padding=0,0,0,0 spacing=1,1')
    fnt_lines.append(f'common lineHeight={line_height} base={ascent} scaleW={tex_w} scaleH={tex_h_pow2} pages=1 packed=0')
    fnt_lines.append(f'page id=0 file="{name}.png"')
    fnt_lines.append(f'chars count={len(positions)}')

    for ch, cx, cy, cw, ch_h, bbox in positions:
        draw.text((cx - bbox[0], cy - bbox[1]), ch, font=font, fill=(255, 255, 255, 255))
        fnt_lines.append(
            f'char id={ord(ch)}   x={cx}     y={cy}     width={cw}    height={ch_h}   '
            f'xoffset={bbox[0]}   yoffset={bbox[1]}   xadvance={cw + 1}  page=0  chnl=15'
        )

    os.makedirs(out_dir, exist_ok=True)
    img.save(os.path.join(out_dir, f"{name}.png"))
    with open(os.path.join(out_dir, f"{name}.fnt"), "w", encoding="utf-8") as f:
        f.write("\n".join(fnt_lines))

    print(f"  {name} @ {size_px}px -> {out_dir}")



BASE = r"C:\Users\yosef\Desktop\garmin app"
BUCKETS = {
    # bucket: (Small, Medium, Large, GlanceSmall, GlanceMedium)
    "resources-mono166":   (17, 22, 26, 20, 26),
    "resources-mip240":    (22, 29, 38, 26, 33),
    "resources-mip280":    (26, 34, 45, 26, 33),
    "resources-amoled360": (32, 44, 56, 34, 44),
}
GLANCE_ONLY = {
    "resources-glance92":    (33, 40),
    "resources-glance103":   (36, 46),
    "resources-glancexover": (14, 18),
}

WIDGET_XML = """    <font id="HebrewSmall"  filename="HebrewSmall.fnt"  />
    <font id="HebrewMedium" filename="HebrewMedium.fnt" />
    <font id="HebrewLarge"  filename="HebrewLarge.fnt"  />
"""
GLANCE_XML = """    <font id="HebrewGlanceSmall"  filename="HebrewGlanceSmall.fnt"  scope="glance" />
    <font id="HebrewGlanceMedium" filename="HebrewGlanceMedium.fnt" scope="glance" />
"""


def write_xml(out, comment, widget):
    with open(os.path.join(out, "fonts.xml"), "w", encoding="utf-8") as f:
        f.write('<?xml version="1.0"?>\n<resources>\n')
        f.write(f"    <!-- {comment} (generated by tools/fonts/generate_fonts_extra.py) -->\n")
        if widget:
            f.write(WIDGET_XML)
        f.write(GLANCE_XML)
        f.write("</resources>\n")


for bucket, (s, m, l, gs, gm) in BUCKETS.items():
    out = os.path.join(BASE, bucket, "fonts")
    generate_fnt("HebrewSmall",  s, out)
    generate_fnt("HebrewMedium", m, out)
    generate_fnt("HebrewLarge",  l, out)
    generate_fnt("HebrewGlanceSmall",  gs, out)
    generate_fnt("HebrewGlanceMedium", gm, out)
    write_xml(out, bucket[len("resources-"):] + " Hebrew bitmap fonts", True)
for bucket, (gs, gm) in GLANCE_ONLY.items():
    out = os.path.join(BASE, bucket, "fonts")
    generate_fnt("HebrewGlanceSmall",  gs, out)
    generate_fnt("HebrewGlanceMedium", gm, out)
    write_xml(out, bucket[len("resources-"):] + " glance-only font override", False)
print("Done!")
